# config.yml
# ----------
# Global hyper-parameters for the FRM + SD pipeline.

# FRM settings
window_days:   63         # rolling window length for FRM (in days)
tau:           0.05       # tail quantile for Lasso regression
step:          5          # step size between windows
lambda_grid:   [0.001, 0.01, 0.1, 1.0, 10.0]
n_folds:       2          # CV folds for Lasso penalty selection
n_jobs:        4          # parallel workers for FRM

# SD test settings
block_len:     10         # block length for block-bootstrapping in SD test
n_boot:        200        # bootstrap replications per pairwise test
alpha_sd:      0.05       # significance level for dominance edges
ngrid:         100        # number of grid points for ECDF in SD test

# Bootstrap-history settings (Step 3b)
H:             21         # look-back length (days) for synthetic histories
B:             50         # number of bootstrap-history draws

# Label creation settings (Step 7)
horizon:       5          # forecast horizon (days ahead) for FRM-jump label
jump_quantile: 0.90       # top quantile threshold for defining a 'jump'
