# FRM_SD_GNN configuration file

# Data frequency and rolling window
frequency: monthly          # Options: 'monthly' or 'weekly'
window: 12                  # Rolling window size (12 months or 52 weeks, etc.)
step: 1                     # Step size for rolling window

# Paths to preprocessed data
returns_path: data/monthly_log_returns.csv   # Or data/weekly_log_returns.csv if freq is weekly
volumes_path: data/monthly_volumes.csv       # Or data/weekly_volumes.csv if freq is weekly

# FRM-ASGL quantile regression parameters
tau: 0.05
lambda_grid: [0.001, 0.01, 0.1, 1, 10]

# Bootstrap (set to 0 for scalar SD network, or >0 for stochastic dominance with bootstrapping)
bootstrap: 0

# Network centrality/factor construction
centrality_metric: eigenvector    # 'indegree', 'outdegree', 'pagerank', or 'eigenvector'
factor_high: 1                   # Number of assets in High-centrality portfolio
factor_low: 1                    # Number of assets in Low-centrality portfolio

# Output locations
lambda_outputs: outputs/lambda_estimates.csv
network_outputs: outputs/networks/               # Directory for network graphs/adjacency
centrality_outputs: outputs/centralities.csv
factor_output: outputs/NetworkRisk.csv

# Regression/factor test settings
regression_window: 30            # Number of rolling periods for factor regressions (optional)


n_jobs: 8